### ISSUE TITLE
Windows Phone 8 

### ISSUE THREAD

**Issue by DRybochkin** [cureos/accord#3]
Hello again.
When I add to the project Accord.Vision error occurs deployment
Optimization of the deployment failed with error "method (s) exceeds the maximum permitted size." you must separate methods

In what could be problem?

Thank you in advance for the reply.

**Comment by cureos** [comment]
I made a Google search, and I spotted that this problem had also been observed [here](https://github.com/erezak/libphonenumber-csharp/issues/1). It seems like WP8 deployment has a size limit on methods. I will give the _Vision_ project a look to see if there are some simple refactorings that could be made. In the time being, do you have any more information from the deployment error?

**Comment by cureos** [comment]
And almost immediately, two strong candidates showed up :-) [FaceHaarCascade](https://github.com/cureos/accord/blob/portable/Sources/Accord.Vision/Detection/Haar%20Cascade/Default/FaceHaarCascade.cs) and [NoseHaarCascade](https://github.com/cureos/accord/blob/portable/Sources/Accord.Vision/Detection/Haar%20Cascade/Default/NoseHaarCascade.cs).

I will investigate how easy it is to move the data of these classes/methods to the library resources to see if such an approach could solve this problem. For the time being, maybe you can exclude these files from the _Accord.Vision_ project and re-build? (I have not tested this myself, so I do not know if the classes are referenced in any code right now.)

**Comment by DRybochkin** [comment]
Unfortunately no. 
I'll try :-)

**Comment by cesarsouza** [comment]
Yeah, those are definitely some strong candidates :-P But those files could also be safely removed from the portable project. The same functionality can be achieved by loading the xml files found in OpenCV using [ HaarCascade.FromXml](http://accord-framework.net/docs/html/M_Accord_Vision_Detection_HaarCascade_FromXml_2.htm). The XML definitions could surely be embedded as resources in the project file, or perhaps distributed along the binaries.

There are other files which may as well violate this maximum size constraint, such as the FAST feature point detector. The problem is that those files have been automatically generated by computer tools, and so they look extremely large, but are also very fast to execute.

**Comment by cureos** [comment]
Thanks, @cesarsouza, I was just about to make a similar comment, glad you could verify my assumptions :-) Just to add, the _OpenCV_ XML files can be found [here](https://github.com/Itseez/opencv/tree/master/data/haarcascades).

**Comment by cesarsouza** [comment]
Yes, and some others (such as the one for the nose) can also be found [here](http://mozart.dis.ulpgc.es/Gias/modesto.html).

**Comment by cureos** [comment]
Great, thanks again Cesar. 

@DRybochkin I will remove the `FaceHaarCascade` and `NoseHaarCascade` classes from the portable _Vision_ project then, hopefully later today. I'll update the files in the prebuilt binaries accordingly. In the meantime, are you able to check whether removing these classes are enough for the _Vision_ assembly to be successfulyy deployed on WP8?

**Comment by cureos** [comment]
Have now removed the predefined _Haar cascades_ from the PCL _Vision_ project. Tested usage and deployment in WP8 project, seemed to work well.

**Comment by cureos** [comment]
@DRybochkin When you have verified that you can include _Accord.Vision_ in your project, please confirm by closing this issue.

Thanks in advance!
Anders

**Comment by DRybochkin** [comment]
Yes you are right.
Thanks
